//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTwitterEntities : DbContext
    {
        public DbTwitterEntities()
            : base("name=DbTwitterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tblBegeniKutusu> tblBegeniKutusu { get; set; }
        public DbSet<tblBegeniler> tblBegeniler { get; set; }
        public DbSet<tblBildirimKutusu> tblBildirimKutusu { get; set; }
        public DbSet<tblBildirimler> tblBildirimler { get; set; }
        public DbSet<tblDM> tblDM { get; set; }
        public DbSet<tblDMKutusu> tblDMKutusu { get; set; }
        public DbSet<tblKullaniciBilgileri> tblKullaniciBilgileri { get; set; }
        public DbSet<tblKullanicilar> tblKullanicilar { get; set; }
        public DbSet<tblTakipci> tblTakipci { get; set; }
        public DbSet<tblTakipciKutusu> tblTakipciKutusu { get; set; }
        public DbSet<tblTakipEdilen> tblTakipEdilen { get; set; }
        public DbSet<tblTakipEdilenKutusu> tblTakipEdilenKutusu { get; set; }
        public DbSet<tblTweetKutusu> tblTweetKutusu { get; set; }
        public DbSet<tblTweetler> tblTweetler { get; set; }
    }
}
