//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBildirimKutusu
    {
        public int BildirimKutusuID { get; set; }
        public int BildirimID { get; set; }
    
        public virtual tblBildirimler tblBildirimler { get; set; }
    }
}
