//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBildirimler
    {
        public tblBildirimler()
        {
            this.tblBildirimKutusu = new HashSet<tblBildirimKutusu>();
            this.tblTakipci = new HashSet<tblTakipci>();
            this.tblTakipEdilen = new HashSet<tblTakipEdilen>();
        }
    
        public int BildirimID { get; set; }
        public string BildirimMesaji { get; set; }
    
        public virtual ICollection<tblBildirimKutusu> tblBildirimKutusu { get; set; }
        public virtual ICollection<tblTakipci> tblTakipci { get; set; }
        public virtual ICollection<tblTakipEdilen> tblTakipEdilen { get; set; }
    }
}
