//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDM
    {
        public tblDM()
        {
            this.tblDMKutusu = new HashSet<tblDMKutusu>();
        }
    
        public int DmID { get; set; }
        public string DmMesajBilgisi { get; set; }
        public int KullaniciBilgileriID { get; set; }
    
        public virtual tblKullaniciBilgileri tblKullaniciBilgileri { get; set; }
        public virtual ICollection<tblDMKutusu> tblDMKutusu { get; set; }
    }
}
