//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTakipEdilen
    {
        public tblTakipEdilen()
        {
            this.tblTakipEdilenKutusu = new HashSet<tblTakipEdilenKutusu>();
        }
    
        public int TakipEdilenID { get; set; }
        public int KullaniciBilgileriID { get; set; }
        public int BildirimID { get; set; }
    
        public virtual tblBildirimler tblBildirimler { get; set; }
        public virtual tblKullaniciBilgileri tblKullaniciBilgileri { get; set; }
        public virtual ICollection<tblTakipEdilenKutusu> tblTakipEdilenKutusu { get; set; }
    }
}
