//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTakipEdilenKutusu
    {
        public int TakipEdilenKutusuID { get; set; }
        public int TakipEdilenID { get; set; }
    
        public virtual tblTakipEdilen tblTakipEdilen { get; set; }
    }
}
